name: CI
on:
  push:
    paths:
      - "tokens.json"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0

      - run: npm ci

      - run: npm run generate

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: convert tokens"
