name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0

      - run: npm ci

      - run: npx token-transformer tokens.json tokens/global.json global --resolveReferences false

      - run: npx token-transformer tokens.json tokens/light.json light --resolveReferences false

      - run: npx token-transformer tokens.json tokens/dark.json dark --resolveReferences false

      - run: npx token-transformer tokens.json tokens/yellow.json yellow --resolveReferences false

      - run: node build.js

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: convert tokens"
